// lib/disposableEmailDomains.ts
//
// Blocklist of disposable / temporary email services. Used at signup
// to refuse free-trial abuse from throw-away addresses.
//
// This is a *defense in depth* layer — combined with one-phone-per-trial
// (enforced on firms.signup_phone) it makes casual abuse expensive.
// Determined attackers can always find a domain we haven't listed; the
// goal is just to deter the easy cases.
//
// Maintenance: when a new service shows up in user reports, add it here.
// We keep the list short and high-signal rather than chasing every
// ephemeral domain on the internet — the phone gate carries most of
// the weight.

const DISPOSABLE_DOMAINS = new Set<string>([
  // Common temp / 10-minute mail services
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "guerrillamail.com",
  "guerrillamail.info",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamail.de",
  "sharklasers.com",
  "grr.la",
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinater.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "temp-mail.org",
  "tempmail.com",
  "tempmail.net",
  "tempmailaddress.com",
  "throwaway.email",
  "throwawaymail.com",
  "trashmail.com",
  "trashmail.net",
  "trashmail.de",
  "getairmail.com",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "discard.email",
  "dispostable.com",
  "tempinbox.com",
  "tempmailo.com",
  "emailondeck.com",
  "spamgourmet.com",
  "spambog.com",
  "mailcatch.com",
  "mailnesia.com",
  "maildrop.cc",
  "moakt.com",
  "incognitomail.org",
  "anonymailbox.com",
  "tempr.email",
  "mt2014.com",
  "burnermail.io",
  "harakirimail.com",
  "spamfighter.cf",
  "spam4.me",
  "byom.de",
  "minuteinbox.com",
  "tafmail.com",
  "yopmail.com",
  "mohmal.com",
  // Aliasing services that are abused for trial-stacking. Note: these
  // also have legitimate users — keep an eye on signup support if you
  // get false-positive complaints.
  "duck.com",
  "anonaddy.com",
  "anonaddy.me",
  "simplelogin.io",
  "simplelogin.co",
  // Catch a few more
  "0-mail.com",
  "33mail.com",
  "armyspy.com",
  "cuvox.de",
  "deadaddress.com",
  "easytrashmail.com",
  "einrot.com",
  "emltmp.com",
  "fastacura.com",
  "fastchevy.com",
  "fastchrysler.com",
  "fastkawasaki.com",
  "fastmazda.com",
  "fastmitsubishi.com",
  "fastnissan.com",
  "fastsubaru.com",
  "fastsuzuki.com",
  "fasttoyota.com",
  "fastyamaha.com",
  "filzmail.com",
  "fivemail.de",
  "gentlemansclub.de",
  "gowikibooks.com",
  "gowikicampus.com",
  "gowikicars.com",
  "gowikifilms.com",
  "gowikigames.com",
  "gowikimusic.com",
  "gowikinetwork.com",
  "gowikitravel.com",
  "gowikitv.com",
  "incognitomail.com",
  "jetable.com",
  "jetable.fr.nf",
  "jetable.net",
  "jetable.org",
  "kasmail.com",
  "klzlk.com",
  "lortemail.dk",
  "mailcatch.com",
  "mailexpire.com",
  "mailmoat.com",
  "mailnull.com",
  "mailtemp.info",
  "mailtothis.com",
  "mailtrash.net",
  "mintemail.com",
  "mt2009.com",
  "mt2014.com",
  "mt2015.com",
  "no-spam.ws",
  "objectmail.com",
  "obobbo.com",
  "pookmail.com",
  "proxymail.eu",
  "rcpt.at",
  "recode.me",
  "recursor.net",
  "rmqkr.net",
  "safe-mail.net",
  "sendspamhere.com",
  "shieldedmail.com",
  "shieldedmail.net",
  "shitmail.me",
  "shortmail.net",
  "skeefmail.com",
  "slopsbox.com",
  "smashmail.de",
  "smellfear.com",
  "snakemail.com",
  "sneakemail.com",
  "snkmail.com",
  "sofimail.com",
  "sogetthis.com",
  "soodonims.com",
  "spamavert.com",
  "spambob.com",
  "spambox.us",
  "spamcannon.com",
  "spamcannon.net",
  "spamcero.com",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgoes.in",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamthis.co.uk",
  "spamthisplease.com",
  "spamtroll.net",
  "speed.1s.fr",
  "supergreatmail.com",
  "supermailer.jp",
  "suremail.info",
  "tagyourself.com",
  "talkinator.com",
  "teleworm.com",
  "teleworm.us",
  "thanksnospam.info",
  "thankyou2010.com",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "tilien.com",
  "tmail.ws",
  "tmailinator.com",
  "toiea.com",
  "trashymail.com",
  "trbvm.com",
  "trialmail.de",
  "tyldd.com",
  "uggsrock.com",
  "veryrealemail.com",
  "viewcastmedia.com",
  "viewcastmedia.net",
  "viewcastmedia.org",
  "vpn.st",
  "wegwerfadresse.de",
  "wegwerfemail.com",
  "wegwerfmail.de",
  "wegwerfmail.info",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wh4f.org",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "yapped.net",
  "yeah.net",
  "yogamaven.com",
  "yuurok.com",
  "zoemail.org",
  "zoemail.net",
  "zoaxe.com",
  "zoemail.com",
]);

export function isDisposableEmail(email: string): boolean {
  const lower = email.toLowerCase().trim();
  const at = lower.lastIndexOf("@");
  if (at < 0) return false;
  const domain = lower.slice(at + 1);
  if (DISPOSABLE_DOMAINS.has(domain)) return true;
  // Match subdomains of blocked roots — e.g. "x.mailinator.com" should
  // also fail.
  for (const d of DISPOSABLE_DOMAINS) {
    if (domain.endsWith("." + d)) return true;
  }
  return false;
}
